# ABSTRACT: Guide for authenticating and authorizing against a PlugAuth server
# VERSION
# PODNAME: PlugAuth::Guide::Client

=head1 DESCRIPTION

This document serves as a guide for writing applications and web services
that authenticate or authorize against a L<PlugAuth> server.

FIXME

=head1 SEE ALSO

L<PlugAuth>, 
L<PlugAuth::Client>, 
L<Authen::Simple::PlugAuth>

=cut
